Miniconda: To make conda operate correctly, please run: 
            source $UCL_CONDA_PATH/etc/profile.d/conda.sh 
Traceback (most recent call last):
  File "main.py", line 561, in <module>
    main()
  File "main.py", line 341, in main
    gen_data_loader.setup()
  File "/home/ucaqkin/.conda/envs/py36tf/lib/python3.6/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/myriadfs/home/ucaqkin/Scratch/nsci0017/code/tg/data_iter.py", line 59, in setup
    self.data = pd.read_csv(self.positive_file, nrows = self.val_size + self.train_size, names = ['smiles'])
  File "/home/ucaqkin/.conda/envs/py36tf/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ucaqkin/.conda/envs/py36tf/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/ucaqkin/.conda/envs/py36tf/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/ucaqkin/.conda/envs/py36tf/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ucaqkin/.conda/envs/py36tf/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/combined_fuel.csv'
